### ISSUE TITLE
Annotation file error when running biotype

### ISSUE THREAD

**Issue by Ben7124** [HCGB-IGTP/XICRA#20]
Hi Jose,

I downloaded the gtf annotation file from https://www.gencodegenes.org/human/ (the first link on that page) labelled gencode.v38.annotation.gtf. When I ran the biotype module, I got the following error. I assume that I need to download a different annotation file? Where can I get that? Thanks again!! -- Ben

Load annotation file gencode.v38.annotation.gtf ...                        ||

ERROR: failed to find the gene identifier attribute in the 9th column of the provided GTF file.
The specified gene identifier attribute is 'transcript_biotype' 
An example of attributes included in your GTF annotation is 'gene_id "ENSG00000223972.5"; transcript_id "ENST00000456328.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "proc
essed_transcript"; transcript_name "DDX11L1-202"; exon_number 1; exon_id "ENSE00002234944.1"; level 2; transcript_support_level "1"; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2"; havana_tran
script "OTTHUMT00000362751.1";' 
The program has to terminate.

**Comment by Ben7124** [comment]
I am re-running it with the primary annotation. Let us see if that works!

**Comment by JFsanchezherrero** [comment]
Hi there, 

I assume you fixed it right? It might be useful if you provide with the annotation file (link) that you use and worked for you. For future users and readers of this thread, basically.

Best regards,
