### ISSUE TITLE
ModuleNotFoundError: No module named 'build.lib'

### ISSUE THREAD

**Issue by ErickMUO** [HCGB-IGTP/XICRA#29]
Hi !

I'm recently trying to use XICRA, but apparently, I can't even run the example (or my own data) because I have some problems through the installation. Here is the error: 

- ModuleNotFoundError: No module named 'build.lib'

Any clue how I could solve it? I am working in a cluster (Debian GNU/Linux 10). I installed XICRA through a conda environment. Also, I installed the build library with anaconda or pip install build. I tried several versions but still, get the same error.

**Comment by JungnamChoLab** [comment]
remove build.lib from XICRA/scripts/RNAbiotype.py

**Comment by JFsanchezherrero** [comment]
Hi there, 

Sorry about the late reply @ErickMUO . I have been out of the office for a while.

Yeah, that fix that @JungnamChoLab  mentioned should do it. I would update XICRA in pip solving this issue and add developments in the piRNA module that I have in a separate branch.

Best regards
