### ISSUE TITLE
ResolvePackageNotFound

### ISSUE THREAD

**Issue by Chenglin20170390** [HCGB-IGTP/XICRA#30]
Hi, I install XICRA by `conda env create -n XICRA -f XICRA_pip/devel/conda/requirements.txt` However, I got the follow errors.
<img width="560" alt="image" src="https://user-images.githubusercontent.com/33062118/155775172-22d6cf3e-3a52-45b6-b8e3-080f0d6dd54e.png">

**Comment by JFsanchezherrero** [comment]
Hi there,

I have updated the XICRA git repo, pip package and conda requirements.

Please pull the repo and try to install again.

Please let me know if you succeeded or you have any additional issues.

Best regards.
