### ISSUE TITLE
ResolvePackageNotFound

### ISSUE THREAD

**Issue by dmi229** [HCGB-IGTP/XICRA#33]
Hello,

I saw someone had posted a similar issue, but I believe I'm working off the latest version that was fixed. I still see this error, eventually I think I linked it to a PC <> Mac issue (https://stackoverflow.com/questions/55554431/conda-fails-to-create-environment-from-yml/55576493#55576493). If it matters, this is a M1 mac. Hope for a fix!

This is my error, thanks in advance!:

ResolvePackageNotFound: 
  - r-r6==2.4.1=r35h6115d3f_0
  - mintmap==2.0.0a0=pypi_0
  - _openmp_mutex==4.5=1_gnu
  - kernel-headers_linux-64==2.6.32=he073ed8_15
  - libuuid==1.0.3=h7f8727e_2
  - r-tidyselect==1.0.0=r35h6115d3f_0
  - lz4-c==1.9.3=h9c3ff4c_1
  - libcblas==3.9.0=8_openblas
  - r-cli==2.0.2=r35h6115d3f_0
  - xlsxwriter==3.0.2=pypi_0
  - biopython==1.79=pypi_0
  - r-farver==2.0.3=r35h0357c0b_0
  - colormath==3.0.0=pypi_0
  - libblas==3.9.0=8_openblas
  - libgfortran4==7.5.0=h14aa051_19
  - pip==21.0.1=py37h06a4308_0
  - htslib==1.12=h9093b5e_1
  - xyzservices==2021.11.0=pypi_0
  - freetype==2.10.4=h0708190_1
  - r-purrr==0.3.4=r35hcdcec82_0
  - libwebp-base==1.2.0=h7f98852_2
  - libstdcxx-devel_linux-64==7.5.0=hb016644_19
  - ca-certificates==2021.10.8=ha878542_0
  - r-glue==1.4.0=r35hcdcec82_0
  - bzip2==1.0.8=h7f98852_4
  - r-stringi==1.4.3=r35h0357c0b_2
  - c-ares==1.17.1=h7f98852_1
  - pcre==8.45=h9c3ff4c_0
  - r-rlang==0.4.5=r35hcdcec82_2
  - tk==8.6.11=h1ccaba5_0
  - multiqc==1.11=pypi_0
  - glib-tools==2.68.3=h9c3ff4c_0
  - lerc==2.2.1=h9c3ff4c_0
  - r-fansi==0.4.1=r35hcdcec82_0
  - fribidi==1.0.10=h36c2ea0_0
  - r-dplyr==0.8.5=r35h0357c0b_0
  - markupsafe==2.0.1=pypi_0
  - libedit==3.1.20191231=he28a2e2_2
  - jbig==2.1=h7f98852_2003
  - tornado==6.1=pypi_0
  - r-zeallot==0.1.0=r35h6115d3f_1001
  - pygments==2.10.0=pypi_0
  - xorg-libsm==1.2.2=h470a237_5
  - libstdcxx-ng==9.3.0=hd4cf53a_17
  - xorg-xextproto==7.3.0=h7f98852_1002
  - isal==0.11.1=pypi_0
  - jpeg==9d=h36c2ea0_0
  - libssh2==1.9.0=ha56f1ee_6
  - gxx_impl_linux-64==7.3.0=hdf63c60_1
  - xz==5.2.5=h7b6447c_0
  - libev==4.33=h516909a_1
  - xorg-libxdmcp==1.1.3=h7f98852_0
  - bwidget==1.9.14=ha770c72_1
  - r-scales==1.1.0=r35h6115d3f_0
  - make==4.3=hd18ef5c_1
  - pthread-stubs==0.4=h36c2ea0_1001
  - xorg-renderproto==0.11.1=h7f98852_1002
  - charset-normalizer==2.0.7=pypi_0
  - gfortran_impl_linux-64==7.3.0=hdf63c60_1
  - pyyaml==5.4.1=pypi_0
  - curl==7.76.1=h979ede3_1
  - networkx==2.6.3=pypi_0
  - r-assertthat==0.2.1=r35h6115d3f_1
  - krb5==1.17.2=h926e7f8_0
  - zipp==3.6.0=pypi_0
  - cairo==1.16.0=h18b612c_1001
  - cutadapt==3.5=pypi_0
  - r-tibble==3.0.1=r35hcdcec82_0
  - fontconfig==2.13.1=h6c09931_0
  - pillow==8.4.0=pypi_0
  - glib==2.68.3=h9c3ff4c_0
  - humanfriendly==10.0=pypi_0
  - r-pkgconfig==2.0.3=r35h6115d3f_0
  - six==1.16.0=pypi_0
  - patool==1.12=pypi_0
  - importlib-metadata==4.8.2=pypi_0
  - numpy==1.21.4=pypi_0
  - typing-extensions==3.10.0.2=pypi_0
  - future==0.18.2=pypi_0
  - r-munsell==0.5.0=r35h6115d3f_1002
  - r-optparse==1.6.6=r35h6115d3f_0
  - r-crayon==1.3.4=r35h6115d3f_1002
  - r-viridislite==0.3.0=r35h6115d3f_1002
  - libnghttp2==1.43.0=h812cca2_0
  - packaging==21.3=pypi_0
  - openssl==1.1.1k=h7f98852_0
  - libgcc-ng==9.3.0=h5101ec6_17
  - samtools==1.12=h9aed4be_1
  - r-rcpp==1.0.4.6=r35h0357c0b_0
  - r-plogr==0.2.0=r35h6115d3f_1002
  - pixman==0.38.0=h516909a_1003
  - mirtop==0.4.23=pypi_0
  - r-ellipsis==0.3.0=r35hcdcec82_0
  - r-backports==1.1.6=r35hcdcec82_1
  - python-dateutil==2.8.2=pypi_0
  - xicra==1.2.6=dev_0
  - click==8.0.3=pypi_0
  - python_abi==3.7=2_cp37m
  - libopenblas==0.3.12=pthreads_hb3c22a3_1
  - _r-mutex==1.0.1=anacondar_1
  - r-colorspace==1.4_1=r35hcdcec82_1
  - commonmark==0.9.1=pypi_0
  - libxcb==1.13=h7f98852_1003
  - r-rcolorbrewer==1.1_2=r35h6115d3f_1002
  - python==3.7.11=h12debd9_0
  - xopen==1.2.1=pypi_0
  - coloredlogs==15.0.1=pypi_0
  - binutils_linux-64==2.33.1=h9595d00_15
  - pandas==1.3.4=pypi_0
  - scipy==1.7.2=pypi_0
  - r-base==3.5.3=h26b83e4_0
  - zstd==1.5.0=ha95c52a_0
  - cycler==0.11.0=pypi_0
  - xorg-xproto==7.0.31=h7f98852_1007
  - pysam==0.17.0=pypi_0
  - binutils_impl_linux-64==2.33.1=he6710b0_7
  - r-xicra.stats==0.0.1=r35_0
  - jinja2==2.11.3=pypi_0
  - gsl==2.4=h294904e_1006
  - gettext==0.19.8.1=h0b5b191_1005
  - xorg-libxext==1.3.4=h7f98852_1
  - libgfortran-ng==7.5.0=h14aa051_19
  - rich==10.13.0=pypi_0
  - bokeh==3.0.0.dev1=pypi_0
  - seaborn==0.11.2=pypi_0
  - libtiff==4.3.0=hf544144_1
  - gcc_linux-64==7.3.0=h553295d_15
  - gxx_linux-64==7.3.0=h553295d_15
  - ncurses==6.2=he6710b0_1
  - kiwisolver==1.3.2=pypi_0
  - libgomp==9.3.0=h5101ec6_17
  - pybedtools==0.8.2=pypi_0
  - libgcc-devel_linux-64==7.5.0=hda03d7c_19
  - graphite2==1.3.13=h58526e2_1001
  - hcgb==0.5.4=dev_0
  - r-vctrs==0.2.4=r35hcdcec82_0
  - gfortran_linux-64==7.3.0=h553295d_15
  - readline==8.1=h27cfd23_0
  - r-getopt==1.20.3=r35_1
  - requests==2.26.0=pypi_0
  - libffi==3.3=he6710b0_2
  - libdeflate==1.7=h7f98852_5
  - libgcc==7.2.0=h69d50b8_2
  - ld_impl_linux-64==2.33.1=h53a641e_7
  - urllib3==1.26.7=pypi_0
  - setuptools==58.0.4=py37h06a4308_0
  - certifi==2021.10.8=py37h89c1867_1
  - colorama==0.4.4=pypi_0
  - libxml2==2.9.12=h03d6c58_0
  - libpng==1.6.37=h21135ba_2
  - xorg-libxau==1.0.9=h7f98852_0
  - lzstring==1.0.4=pypi_0
  - libcurl==7.76.1=hc4aaa36_1
  - xorg-libxrender==0.9.10=h7f98852_1003
  - r-utf8==1.1.4=r35hcdcec82_1002
  - matplotlib==3.4.3=pypi_0
  - xorg-libice==1.0.10=h7f98852_0
  - spectra==0.0.11=pypi_0
  - gcc_impl_linux-64==7.3.0=habb00fd_1
  - r-lifecycle==0.2.0=r35h6115d3f_0
  - pyparsing==3.0.5=pypi_0
  - tesmall==1.0.0=pypi_0
  - zlib==1.2.11=h7b6447c_3
  - xorg-libx11==1.7.2=h7f98852_0
  - dnaio==0.6.0=pypi_0
  - markdown==3.3.4=pypi_0
  - icu==58.2=hf484d3e_1000
  - r-tidyr==1.0.2=r35h0357c0b_0
  - harfbuzz==2.4.0=h37c48d4_1
  - libiconv==1.16=h516909a_0
  - simplejson==3.17.5=pypi_0
  - pytz==2021.3=pypi_0
  - sqlite==3.36.0=hc218d9a_0
  - tktable==2.10=hb7b940f_3
  - wget==3.2=pypi_0
  - r-magrittr==1.5=r35h6115d3f_1002
  - r-pillar==1.4.3=r35h6115d3f_0
  - r-labeling==0.3=r35h6115d3f_1002
  - r-digest==0.6.25=r35h0357c0b_1
  - idna==3.3=pypi_0
  - sysroot_linux-64==2.12=he073ed8_15
  - pango==1.42.4=h7062337_4
  - libglib==2.68.3=h3e27bee_0
  - star==2.7.9a=h9ee0642_0
  - xorg-kbproto==1.0.7=h7f98852_1002
  - termcolor==1.1.0=pypi_0

**Comment by JFsanchezherrero** [comment]
Hi there,
I am not able to test in Mac whether XICRA works or not. But I guess it should work if conda works fine.
I will be updating soon the package. I will let you know so that you can fresh install it.

Regards

**Comment by JFsanchezherrero** [comment]
Hi there,
I have been working on the new installation.

Please do as follows and let me know it it worked.

Best regards,



1) Get requirements file from XICRA git repo

```sh
wget https://raw.githubusercontent.com/HCGB-IGTP/XICRA/master/XICRA_pip/devel/conda/environment.yml
```

2) Create environment named XICRA and install required packages using conda: 

```sh
conda env create -f environment.yml
```

3) Activate environment and install XICRA
```sh
## activate
conda activate XICRA

## install latest python code
pip install XICRA
```

4) Install missing software:  Unfortunately, a couple of executables are not available neither as a `conda` or `pip` packages. These packages are `miraligner`, `sRNAbench` and 'MINTmap'. We have generated a `bash` script to retrieve and include within your `conda environment`.

```sh
## install missing software
wget https://raw.githubusercontent.com/HCGB-IGTP/XICRA/master/XICRA_pip/XICRA/config/software/installer.sh
sh installer.sh
```

To check everything is fine, try executing the `config` module:
```sh
XICRA config
```
