### ISSUE TITLE
How to install it properly

### ISSUE THREAD

**Issue by Ben7124** [HCGB-IGTP/XICRA#36]
Hello,
I also get the resolve package not found when I type:

conda env create -n XICRA -f XICRA_pip/devel/conda/requirements.txt

But when I do this to install (from here: https://github.com/HCGB-IGTP/XICRA/tree/master/XICRA_pip#example) , it seems to work, but miraligner does not work. What is the correct way to install XICRA since there seems to be a few different ways to do it. Thanks for your help!

Get requirements file from XICRA git repo
wget https://raw.githubusercontent.com/HCGB-IGTP/XICRA/master/XICRA_pip/devel/conda/environment.yml
Create environment and install required packages using conda:
conda env create -n XICRA -f environment.yml
Activate environment and install XICRA
## activate
conda activate XICRA

## install latest python code
pip install XICRA
Install missing software: Unfortunately, a couple of executables are not available neither as a conda or pip packages. These packages are miraligner and sRNAbench. We have generated a shell script to retrieve and include within your conda environment.
## install missing software
sh XICRA_pip/XICRA/config/software/installer.sh

**Comment by JFsanchezherrero** [comment]
Hi there, 

Thanks for using XICRA and pointing this out. Sorry for the several options to install it. We tried to explain it but it seems like it is not clear. We will work on it. The thing is that XICRA has many softwares within and miraligner is not available either as conda package, pip or any other similar. So basically I created a shell script that downloads it and places within the conda environment path activated.

I would suggest to follow the steps:

```
## clone repo
git clone https://github.com/HCGB-IGTP/XICRA.git

## create conda environment using requirements.txt file
conda env create -n XICRA -f XICRA/XICRA_pip/devel/conda/requirements.txt

## activate
conda activate XICRA

## install latest python code
pip install XICRA

## install missing software
sh XICRA/XICRA_pip/XICRA/config/software/installer.sh

## Check everything is fine with
XICRA config
```

Please let me know if you finally manage to install it.

It would be great in creating a full conda environment that you can just install it in a single sentence but I am able to set a time yet.

Best regards

**Comment by Ben7124** [comment]
Thanks for your reply! I get the ResolvePackageNotFound after I type:

conda env create -n XICRA -f XICRA/XICRA_pip/devel/conda/requirements.txt

Is there anything I can do to fix this?

**Comment by JFsanchezherrero** [comment]
Hi there Ben,
I have been working on the new installation.

Please do as follows and let me know it it worked.

Best regards,



1) Get requirements file from XICRA git repo

```sh
wget https://raw.githubusercontent.com/HCGB-IGTP/XICRA/master/XICRA_pip/devel/conda/environment.yml
```

2) Create environment named XICRA and install required packages using conda: 

```sh
conda env create -f environment.yml
```

3) Activate environment and install XICRA
```sh
## activate
conda activate XICRA

## install latest python code
pip install XICRA
```

4) Install missing software:  Unfortunately, a couple of executables are not available neither as a `conda` or `pip` packages. These packages are `miraligner`, `sRNAbench` and 'MINTmap'. We have generated a `bash` script to retrieve and include within your `conda environment`.

```sh
## install missing software
wget https://raw.githubusercontent.com/HCGB-IGTP/XICRA/master/XICRA_pip/XICRA/config/software/installer.sh
sh installer.sh
```

To check everything is fine, try executing the `config` module:
```sh
XICRA config
```

**Comment by Ben7124** [comment]
Hi,
I followed the steps above and I get the error below for fastqc. Does pip install install fastqc as well? Thanks!

++++++++++++++++++++
External dependencies:
++++++++++++++++++++

**ERROR: Software fastqc could not be found.

**Comment by JFsanchezherrero** [comment]
Hi there,
Sorry for that. I guess I forget it.

Try:
`conda install -c bioconda fastqc`

I will update environment yml file too.

Let me know if any issues please.

Thanks for the debugging.
Regards

**Comment by Ben7124** [comment]
Hi again!
I installed fastqc and I installed the other packages, but after the package check where all is fine, I get a Python error below:
Sorry for all the trouble!

++++++++++++++++++++
Python packages:
++++++++++++++++++++
Traceback (most recent call last):
  File "/home/ubu/miniconda3/envs/XICRA/bin/XICRA", line 382, in <module>
    args.func(args)
  File "/home/ubu/miniconda3/envs/XICRA/lib/python3.7/site-packages/XICRA/modules/config.py", line 68, in run_config
    set_config.check_python_packages(Debug)
  File "/home/ubu/miniconda3/envs/XICRA/lib/python3.7/site-packages/XICRA/config/set_config.py", line 383, in check_python_packages
    my_packages_installed = get_python_packages(Debug)
  File "/home/ubu/miniconda3/envs/XICRA/lib/python3.7/site-packages/XICRA/config/set_config.py", line 356, in get_python_packages
    module_dependencies = functions.main_functions.file2dictionary(file_module_dependecies, ',')
  File "/home/ubu/miniconda3/envs/XICRA/lib/python3.7/site-packages/HCGB/functions/main_functions.py", line 81, in file2dictionary
    (key, val) = line.split(split_char)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by JFsanchezherrero** [comment]
Hi there,
Can you check again? 
I updated and fixed some errors recently.

Make sure you are using version 1.4.4

**Comment by Ben7124** [comment]
Hi,

I am able to properly install it now, but I get an error in the miRNA module. I will start a new issue and close this one. Thank you!
