### ISSUE TITLE
Missing import XICRA.modules.database in modules/tRNA.py

### ISSUE THREAD

**Issue by cplessis** [HCGB-IGTP/XICRA#37]
Hi ! 

I've got import error message: 

```
File "/usr/local/lib/python3.8/dist-packages/XICRA/modules/tRNA.py", line 131, in run_tRNA
    options.tRNA_db = database.tRNA_db(options.database, options.tRNA_db, options.debug)    
NameError: name 'database' is not defined
```

It would be great to fix it, thanks :)

**Comment by JFsanchezherrero** [comment]
Hi there,
I think I have fixed the issue. I can not reproduce the error in my laptop now so please let me know if you suceed to work it out or you encounter any additional errors.

Please, re-install XICRA via pip and make sure v1.4.3 is installed.

Best regards
Jose

**Comment by cplessis** [comment]
Hi Jose, 

There is a new error now:

```
Traceback (most recent call last):
  File "/usr/local/bin/XICRA", line 382, in <module>
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/XICRA/modules/tRNA.py", line 132, in run_tRNA
    options.tRNA_db = database.tRNA_db(options.database, options.tRNA_db, options.debug)    
AttributeError: 'Namespace' object has no attribute 'tRNA_db'
```
Thanks

Clement

**Comment by JFsanchezherrero** [comment]
Hi there,
I see where the problem is. I will fix it tomorrow and let you know.

Best regards and hope you find XICRA useful,
Jose

**Comment by JFsanchezherrero** [comment]
Hi there,
I guess I have fixed it. Make sure to install version 1.4.5.
I have found some missing packages not included in the YML file so it might be useful to update your conda environment too.

I have additionally added a test set of reads, either for miRNA or tRNA modules. Run `XICRA test` and then try either to run the shell script generated or step by step. Be aware some of the reads are either simulated or trimmed and might produce errors during trimming.

The tRNA module is working fine for me now,

Please, again, if any errors or doubts arise, please let me know.

**Comment by JFsanchezherrero** [comment]
Hi there @cplessis, I wonder if you found any other issues?
Best regards
