### ISSUE TITLE
Biotype and featureCounts argument

### ISSUE THREAD

**Issue by jonahcullen** [HCGB-IGTP/XICRA#38]
Hello, thank you for putting together this fantastic pipeline, I have been having fun digging through it all. I am processing PE small RNA-seq data through prep, QC, and trimm.

I had one question regarding the biotype module and specifically with featureCounts. Why is the `-p` flag included? I can see in the featureCounts doc that is for counting fragments instead of reads and is only applicable for PE reads (SE reads always counted as reads). I noticed with this flag included, it returns 0% _Successfully assigned alignments_, compared to without at >80%.

Perhaps I am misunderstanding the impact or purpose rather?

Thanks for your time,
Jonah.

**Comment by JFsanchezherrero** [comment]
Hi there Jonah,
I am glad to hear you find interesting and useful this pipeline.

I can see you opened another issue, I will be answering there later too. 

Regarding the question you mentioned here about the biotype and featurecount flag I set `-p` as I understood is required for counting BAM files mapped using paired-end. It is true that it might not be required and if it produces these differences in statistics that you mentioned it definitely makes no sense to keep it.

I will further test and read about it and change it or maybe set it as optional in future versions of XICRA.

Thanks for your time too
Best regards,

**Comment by jonahcullen** [comment]
Thank you for your prompt response!
