### ISSUE TITLE
No such file or directory when doing miRNA analysis

### ISSUE THREAD

**Issue by Ben7124** [HCGB-IGTP/XICRA#40]
Hello,

When running the miRNA module with the command: XICRA miRNA --input datafolder --software miraligner optimir sRNAbench
I get the following error:

Can you please help me troubleshoot the issue? Thank you!

--------- Starting Process ---------
        09/19/2022, 09:22:31

+ Software for miRNA analysis selected:
['miraligner', 'optimir', 'sRNAbench']
+ Getting files from input folder...
+ Mode: join.
+ Extension:
[_joined.fastq]

+ Input folder exists
        12 files selected...
        12 samples selected...
        Single end mode selected...
+ Species provided: hsa
+ Create folder to store results:  /home/ubu/miniconda3/envs/XICRA/lib/python3.7/site-packages/XICRA/modules/db_files
        + miRNA gff file available
        + hairpin fasta file available
        + miRNA gff file available
        + miRBase str file available
+ Create a miRNA analysis for each sample retrieved...
***ERROR:
<Future at 0x7fe75ee55550 state=finished raised FileNotFoundError>
'CONTROL_1' generated an exception: [Errno 2] No such file or directory: '/home/ubu/datafolder/data/CONTROL_1/miRNA/miraligner/CONTROL_1-tab.freq.txt'

same error here for all samples......

+ miRNA analysis is finished...
+ Let's summarize all results...
+ Input folder exists

**ERROR: No samples were retrieved for this option. Continue processing...

**Comment by Ben7124** [comment]
Works now!

**Comment by JFsanchezherrero** [comment]
Hi there, 
Happy to hear it worked.

thanks for the feedback!
Best regards
