### ISSUE TITLE
How to perform differential expression

### ISSUE THREAD

**Issue by Ben7124** [HCGB-IGTP/XICRA#41]
Hello,

I have used the XICRA miRNA pipeline to identify several miRNAs, but now I want to use the pipeline to output differential expression results between each pair of samples. How do I do this within XICRA?

Thank you for your help!

**Comment by JFsanchezherrero** [comment]
Hi there @Ben7124,

I am afraid we do not include per se this type of analysis. XICRA ends generating a maxtrix for the differential expression analysis, but we do not include it here.

You can find the matrix in file `report/miRNA/miRNA_expression-***.csv` (*** stands for the software you chose: miraligner, optimir, sRNAbench). This matrix contains as columns the sample names and as rows the isomiRs identified.

This file would be the input for other differential expression analysis such as DESeq2, limma in R.

We also created `XICRA.stats` that basically loads the matrix and summarizes information into variant, miRNA or isomir. See information [here](https://github.com/HCGB-IGTP/XICRA.stats) and install it by typing:
```R
# Install XICRA.stats version from GitHub:
# install.packages("devtools")
devtools::install_github("HCGB-IGTP/XICRA.stats")
```
Then, you can do something like this:
```R
## loads data, sample sheet and prepares
XICRA_data <- XICRA.stats::parse_XICRA(XICRA_csv_file)
```

XICRA_data is a list with 3 different dataframes containing different information:

**1. XICRA_data$miRNA_data:** Data summarized for each miRNA, no matter the isoform (all counts for each miRNA as added together)
**2. XICRA_data$isomir_data:** Information summarized for each isomiR. 
**3. XICRA_data$variant_data:** Information summarized for each variant type, following miRTop nomenclature

Please take into account that isomiR counts are generated for each variant of each miRNA. The canonical miRNA is considered as a variant too (NA variant). Read further details [here](https://github.com/HCGB-IGTP/XICRA/blob/master/XICRA_pip/docs/source/user_guide/modules/miRNA.rst) and in the original publication.

I usually do analysis at the isomir level using DESeq2. Read further information [here](http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html) and [here](http://master.bioconductor.org/packages/release/workflows/vignettes/rnaseqGene/inst/doc/rnaseqGene.html). So, I use XICRA_data$isomir_data as the count data for the DESeq2 DESeqDataSetFromMatrix function.

```R
ddsFullCountTable <- DESeq2::DESeqDataSetFromMatrix(
    countData = XICRA_data$isomir_data,
    colData = sample_sheet, 
    design = as.formula('~condition') )
  
dds_object <- DESeq2::DESeq(ddsFullCountTable, parallel = TRUE)

## exploratory
vsd <- DESeq2::varianceStabilizingTransformation(dds_object, blind = FALSE)
plt_pca <- DESeq2::plotPCA(vsd, intgroup="condition")

distsRL <- dist(t(assay(vsd)))
mat <- as.matrix(distsRL)
sampleDist <- pheatmap::pheatmap(mat, annotation = sample_sheet)

## get DE results
print(resultsNames(dds_object))
normValues <- counts(dds_object, normalized=T)

 sign.data<-alldata[alldata$padj<0.05,]
sign.data<-sign.data[!is.na(sign.data$padj),]
sign.data<-sign.data[abs(  sign.data$log2FoldChange)>log2(1.2),]
sign.data <- sign.data[order(sign.data$padj),]


```
This is a very simplified and naive scheme. Please, read carefully about the DE analysis and all the possibilities and results DESeq2 or any other packages can generate.

I hope it helps,
Best regards

Jose
