### ISSUE TITLE
log of commands

### ISSUE THREAD

**Issue by EmeTexe** [HCGB-IGTP/XICRA#44]
Hello,

Thank you for the tool.

I wanted to know if there is any log where I can check which commands where launched by XICRA, and the exact parameters used for the command? I checked the logs generated by test_subset.sh, but only found some of the commands used (mainly multiqc).

Thanks for your time,
Emeric

**Comment by JFsanchezherrero** [comment]
Hi there Emeric,
Thanks for trying XICRA.

You should have a new folder generated where you executed the `test_subset.sh` file named as logs/ containing several information. 

Also, if you check the file` test_subset.sh `these are the XICRA commands executed, as an example for the singe-end reads provided.

```
## prepare reads, folders and subfolders
XICRA prep -i ./subset_SE/ -o XICRA_analysis --single_end | tee logs/XICRA_analysis.prep.log

## Quality check
XICRA QC -i XICRA_analysis --single_end --threads 4 | tee logs/XICRA_analysis.qc.log

## trim any adapters
XICRA trim -i XICRA_analysis --single_end --threads 4 --adapters_a TGGAATTCTCGGGTGCCAAGG | tee logs/XICRA_analysis.trim.log

## create miRNA analysis
XICRA miRNA -i XICRA_analysis --single_end --threads 4 --software miraligner | tee logs/XICRA_analysis.miRNA.log

```

Take into account that the  `| tee  whatever_file.log` allows us to see the output in screen and print it in a file. Check these files for additional details.

I hope I have answered your questions. Do not hesitate to contact us again.
Best regards

**Comment by EmeTexe** [comment]
Hi,

Thanks for your answer!

What I want to know is the commands launched by XICRA. What are the parameters used for STAR, cutadapt, miRTop... I couldn't find this information in any of the log files.

Best regards,

Emeric

**Comment by JFsanchezherrero** [comment]
Hi there Emeric,

I think you should be able to find this information in the logs file mentioned. 

I would say that every single time we call the system to call any third party software, we use the same code that creates these type of messages coloured coded:

![Screenshot from 2023-04-17 16-18-39](https://user-images.githubusercontent.com/20244642/232515246-bd1065d3-54f3-49c1-9d07-52e54457f73a.png)


So you can track all the parameters and options applied, full absolute paths etc

Please take a look an let me know if not. Did it work succesfully? Has the counts file  been generated in folder `report/miRNA`?

Best regards

**Comment by EmeTexe** [comment]
Hi,

Seems like my logs had a problem, I reran the test_subset.sh after cleaning the outputs, and now have the commands with their parameters in the logs.

Thank you for your time,
Best regards

Emeric

**Comment by JFsanchezherrero** [comment]
Great!
Do not hesitate to contact us again.

Best regards

**Comment by EmeTexe** [comment]
Hi, 
I have another question. In the `XICRA_analysis_PE.miRNA.log` file, there is this file `XICRA_test_dir/XICRA_analysis_PE/data/rep_1/miRNA/miraligner/rep_1-tab.freq.txt` which is used as input for `miraligner`, but there is nowhere in the logs that says how it was generated. How is it generated, and what exactly is inside?

best regards,
Emeric

**Comment by JFsanchezherrero** [comment]
Hi there Emeric,
The step that you mention is a preprocessing of the reads to create a frequency table to input into miraligner. This process is coded within the XICRA script here: 
https://github.com/HCGB-IGTP/XICRA/blob/6e9b4121f27cd60bb5640934eab16bd27c572395/XICRA_pip/XICRA/scripts/miraligner_caller.py#L85-L86

where we basically called this function `reads2tabular` to create a dictionary from the reads with information of the frequency of each sequence identified.

The `reads2tabular` function is included in a secondary python package (`HCGB`) that we also develop. See details [here](https://github.com/HCGB-IGTP/HCGB_python_functions/blob/80c1779404293343bdf9cc6b0288682f925e8508/HCGB/functions/fasta_functions.py#L132)

Best regards,

**Comment by EmeTexe** [comment]
Hi,

Thank you for your answer! It says on the miraligner documentation that it can take fastq files as input, why did you chose to use a frequency table instead of simply the fastq from fastq-join?

Best regards,
Emeric

**Comment by JFsanchezherrero** [comment]
Hi Emeric, 
I can not remember right now (several years ago) but I have the feeling there was an issue when using the fastq option that prevent us from using as a default.

We basically converted the fastq-join (or single-end fastq file) into this frequency table to use it as an input into miraligner.

Best regards
